# fly.toml app configuration file for Twiper

app = "twiper"
primary_region = "iad"

[build]

[env]
  LOG_LEVEL = "INFO"

# No services or processes defined.
# This app runs cron inside the container.
